package com.webbfontaine.efem.constants

final class PrintConstants {

    static String IS_IGNORE_CELL_BORDER = 'IS_IGNORE_CELL_BORDER'
    static String IS_REMOVE_EMPTY_SPACE_BETWEEN_COLUMNS='IS_REMOVE_EMPTY_SPACE_BETWEEN_COLUMNS'
    static String IS_REMOVE_EMPTY_SPACE_BETWEEN_ROWS = 'IS_REMOVE_EMPTY_SPACE_BETWEEN_ROWS'
    static String IS_COLLAPSE_ROW_SPAN='IS_COLLAPSE_ROW_SPAN'
    static String IGNORE_PAGE_MARGINS='IGNORE_PAGE_MARGINS'
    static String IS_DETECT_CELL_TYPE ='IS_DETECT_CELL_TYPE'
    static String IS_IGNORE_PAGINATION='IS_IGNORE_PAGINATION'
}
